all:
  hosts:
    node1:
      ansible_host: 192.168.1.10
    node2:
      ansible_host: 192.168.1.11
    node3:
      ansible_host: 192.168.1.12

  children:
    clickhouse:
      hosts:
        node1:
        node2:
        node3:

