[servers]
db1.server.local 
db2.server.local 
db3.server.local 
db4.server.local 
db5.server.local 
db6.server.local 

[keeper]
keeper1.server.local
keeper2.server.local
keeper3.server.local


[cluster:children]
keeper
servers
