---
- name: Deploy ClickHouse config.xml
  template:
    src: config.xml.j2
    dest: /etc/clickhouse-server/config.xml
    owner: clickhouse
    group: clickhouse
    mode: 0644

- name: Deploy ClickHouse users.xml
  template:
    src: users.xml.j2
    dest: /etc/clickhouse-server/users.xml
    owner: clickhouse
    group: clickhouse
    mode: 0644

